Update sync.yml

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -28,23 +28,32 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install pandas requests pyyaml
+    - name: Download content
+      run: |
+        URL="https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/adservers.txt"
+        OUTPUT_FILE="./rule/adservers.txt"
+
+        curl -L $URL -o $OUTPUT_FILE
+
+        if [ -f "$OUTPUT_FILE" ]; then
+          echo "Download successful: $OUTPUT_FILE"
+        else
+          echo "Download failed."
+          exit 1
+        fi
+    - name: Convert AdGuard DNS Filter to sing-box rule set
+      run: |
+        sing-box rule-set convert --type adguard --output ./rule/adservers.srs ./rule/adservers.txt
     - name: Run script
-      run: python main.py
-      working-directory: .  # 根目录下运行脚本
+      run: python ../main.py
+      working-directory: ./rule/
     - name: Commit and push config.json
       run: |
         git config --global user.email "action@github.com"
         git config --global user.name "GitHub Action"
-
-        # 检查并添加 .txt 文件
-        if ls ./rule/*.txt 1> /dev/null 2>&1; then
-          git add ./rule/*.txt
-        else
-          echo "No .txt files to add."
-        fi
-
         git add ./rule/*.json
         git add ./rule/*.srs
+        git add ./rule/*.txt
 
         # 检查是否有文件被修改
         if git diff --staged --quiet; then
